import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';

function Paragraph(props) {
  return (
    <>
      <p>{props.id}: {props.title}</p>
    </>
  );
}

function Card(props) {
  const [likes, setLikes] = useState(-1);

  if (likes === -1) {
    return (
      <div className="card col-4 d-flex justify-content-center">
        <button onClick={() => { setLikes(likes + 1) }} href="#" className="btn btn-primary">
          Click to reveal Puritan
        </button>
      </div>
    );
  }

  return (
    <>
      <div className="card col-4 d-flex justify-content-center">
        <img src={props.src} className="card-img-top" alt="..." />
        <div className="card-body">
          <Link href={{pathname: "pokemons/[id]", query:{id:props.id}}}>
          <h5 className="card-title">{props.title}</h5>
          </Link>
          <p className="card-text">{props.text}</p>
          {likes === 5 ? null : (
            <>
              <p className="card-text">Likes: {likes}</p>
              <button onClick={() => { setLikes(likes + 1) }} href="#" className="btn btn-primary">
                {props.buttonText}
              </button>
            </>
          )}
        </div>
      </div>
    </>
  );
}

function App() {
  const [VerseList, setVerseList] = useState([]);
  const [offset, setOffset] = useState(0);
  const [isLoading, setIsLoading] = useState(false);
  const limit = 20;
  useEffect(() => {
    setIsLoading(true);
    fetch(`https://pokeapi.co/api/v2/pokemon?offset=${offset}$limit=${limit}`)
      .then(response => {
        return response.json();
      })
      .then(json => {
        setIsLoading(false);
        setVerseList([...VerseList, ...json['results']]); //adds all the 'more' pokemon to the full list
      })
  }, [offset]) //tells UseEffect to run once

  return (
    <div className="App">
      <div className="container">
        <div className="row">
          {VerseList?.map(verse => { //map transforms items in the list into another item
            const id = getIDFromPokemon(verse);
            return (
            <Card
              id={id}
              title={verse['name']}
              text="Scholar"
              buttonText="like"
              src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`}
            />);
  })}
        </div>
        {isLoading == true ? <div class="spinner-border" role="status">
          <span class="visually-hidden">Loading...</span>
        </div> : null}
      <div></div>
        <button onClick={() => { setOffset(offset + limit) }}>More</button>
      </div>
    </div>
  );

}

function getIDFromPokemon(pokemon) {
  return pokemon.url.replace(
    "https://pokeapi.co/api/v2/pokemon/",
    ""
  ).replace('/', '');

}

export default App;


// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <h1 className={styles.title}>
//           Welcome to <Link href="/lucas">Lucas</Link>
//         </h1>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>pages/index.js</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
